version: "3"

services:

  testhost:
    build:
      dockerfile: testHost.Dockerfile
      context: .
    environment:
      - NODE_ENV=local_docker
    depends_on:
      - frontend

  frontend:
    build:
      dockerfile: frontEnd.Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=local_docker
    depends_on:
      - redis

  redis:
    image: redis
